basicexpressreactframework:
  image: vincentlinsanity/basicexpressreactframework:latest
  links:
    - "mongo:mongo"
    - "redis:redis"
  ports:
    - "3000:3000"
    - "443:443"
mongo:
  image: vincentlinsanity/mongodb:3.0.3
  expose:
    - 27017
  volumes:
    - '/home/docker/compose/meta/data/mongo:/data/db'
redis:
  image: vincentlinsanity/redis:3.0.3
  expose:
    - 6379
  volumes:
    - '/home/docker/compose/meta/data/redis:/data'